apiVersion: v1
kind: Service
metadata:
  name: fio-report
  labels:
    app: fio-storage
spec:
  selector:
    app: fio-storage
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fio-report
spec:
  ingressClassName: nginx
  rules:
    - host: report.local.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fio-report
                port:
                  number: 80
